name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m venv backend/venv
        ./backend/venv/bin/pip3 install -r backend/requirements.txt
    - name: Cache pre-commit hooks
      uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: ${{ runner.os }}-precommit-${{ hashFiles('.pre-commit-config.yaml') }}
    - name: Install pre-commit
      run: ./backend/venv/bin/pip3 install pre-commit
    - name: Run pre-commit
      run: ./backend/venv/bin/pre-commit run --all-files
